name: HunterVSSpeedrunner
main: miqhtie.huntervsspeedrunner.Main
version: 1.0.5

author: Miqhtie
description: A custom Hunter vs Speedrunner plugin

commands:
  hunter:
    description: Makes you a hunter!
  speedrunner:
    description: Makes you a speed runner!
  listpeople:
    description: Lists all Hunters/Speedrunners!
  start:
    description: Starts the game!
  track:
    description: Tracks speedrunners if you are a hunter
  teamates:
    description: Tells you the location of your teamates
  onepunch:
    description: Activates 1pm mode. ALL HUNTERS ONE HIT SPEEDRUNNERS!
  quitteam:
    description: If you are a hunter you are now not a hunter, if you are a speed runner you are now not a speed runner.